# Site settings
title: Uni Light Studio
email: info@unilightstudio.com
description: "Uni Light Studio is a production company based in Los Angeles dedicated to creating beauty in commercial and experimental digital media."
baseurl: ""
url: "http://yourdomain.com"
twitter_username: unilightstudio
github_username:  unilightstudio

# Build settings
markdown: kramdown
permalink: pretty
